FROM amazon/aws-lambda-python:3.12 as build
RUN dnf install -y unzip && \
    curl -Lo "/tmp/chromedriver-linux64.zip" "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.85/linux64/chromedriver-linux64.zip" && \
    curl -Lo "/tmp/chrome-linux64.zip" "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.85/linux64/chrome-linux64.zip" && \
    unzip /tmp/chromedriver-linux64.zip -d /opt/ && \
    unzip /tmp/chrome-linux64.zip -d /opt/

FROM amazon/aws-lambda-python:3.12
RUN dnf install -y atk cups-libs gtk3 libXcomposite alsa-lib \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel nss mesa-libgbm
RUN dnf install fedora-workstation-repositories
RUN dnf config-manager --set-enabled google-chrome
RUN dnf install google-chrome-stable
RUN pip install selenium==4.27.1 beautifulsoup4 boto3 selenium-base
RUN seleniumbase get chromedriver --path
COPY main.py ./
CMD [ "python3", "main.lambda_handler" ]
    