name: demo-test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - feat/github-actions**

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-prod-stack

jobs:
  demo-test:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-1
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Demo README's instructions
        run: |
          npm install -g serverless@^3
          sls create --template-url "https://github.com/umihico/docker-selenium-lambda/tree/main" --path docker-selenium-lambda && cd $_
          sls deploy
          sls invoke --function demo |& tee /tmp/scraping-result.txt
          cat /tmp/scraping-result.txt | grep -q "This domain is for use in illustrative examples in documents"
